### ISSUE TITLE
Game Error

### ISSUE THREAD

**Issue by DemOnJR** [blackdragonx61/Metin2-Remote-Shop#1]
Is missing some import? because i get this error on compiling
`input_main.cpp: In member function 'void CInputMain::RemoteShop(LPCHARACTER, const char*)':
input_main.cpp:2289:75: error: 'max' was not declared in this scope; did you mean 'std::max'?
 2289 |   ch->ChatPacket(CHAT_TYPE_INFO, "<RemoteShop> You have to wait %u sec.", max(1, (dwLimitTime - dwCurrentTime) / 1000));
      |                                                                           ^~~
      |                                                                           std::max
compiling log.cpp
In file included from /usr/local/lib/gcc9/include/c++/algorithm:62,
                 from stdafx.h:19,
                 from input_main.cpp:1:
/usr/local/lib/gcc9/include/c++/bits/stl_algo.h:3462:5: note: 'std::max' declared here
 3462 |     max(initializer_list<_Tp> __l, _Compare __comp)
`

if i chage it to **std::max** i get this:
`input_main.cpp: In member function 'void CInputMain::RemoteShop(LPCHARACTER, const char*)':
input_main.cpp:2289:123: error: no matching function for call to 'max(int, unsigned int)'
 2289 |   ch->ChatPacket(CHAT_TYPE_INFO, "<RemoteShop> You have to wait %u sec.", std::max(1, (dwLimitTime - dwCurrentTime) / 1000));
      |                                                                                                                           ^
compiling lzo_manager.cpp
In file included from /usr/local/lib/gcc9/include/c++/bits/char_traits.h:39,
                 from /usr/local/lib/gcc9/include/c++/string:40,
                 from ../../../Extern/include/msl/utils.h:18,
                 from ../../common/utils.h:1,
                 from stdafx.h:15,
                 from input_main.cpp:1:
/usr/local/lib/gcc9/include/c++/bits/stl_algobase.h:222:5: note: candidate: 'template<class _Tp> const _Tp& std::max(const _Tp&, const _T                      p&)'
  222 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
/usr/local/lib/gcc9/include/c++/bits/stl_algobase.h:222:5: note:   template argument deduction/substitution failed:
input_main.cpp:2289:123: note:   deduced conflicting types for parameter 'const _Tp' ('int' and 'unsigned int')
 2289 |   ch->ChatPacket(CHAT_TYPE_INFO, "<RemoteShop> You have to wait %u sec.", std::max(1, (dwLimitTime - dwCurrentTime) / 1000));
      |                                                                                                                           ^
In file included from /usr/local/lib/gcc9/include/c++/bits/char_traits.h:39,
                 from /usr/local/lib/gcc9/include/c++/string:40,
                 from ../../../Extern/include/msl/utils.h:18,
                 from ../../common/utils.h:1,
                 from stdafx.h:15,
                 from input_main.cpp:1:
/usr/local/lib/gcc9/include/c++/bits/stl_algobase.h:268:5: note: candidate: 'template<class _Tp, class _Compare> const _Tp& std::max(cons                      t _Tp&, const _Tp&, _Compare)'
  268 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
/usr/local/lib/gcc9/include/c++/bits/stl_algobase.h:268:5: note:   template argument deduction/substitution failed:
input_main.cpp:2289:123: note:   deduced conflicting types for parameter 'const _Tp' ('int' and 'unsigned int')
 2289 |   ch->ChatPacket(CHAT_TYPE_INFO, "<RemoteShop> You have to wait %u sec.", std::max(1, (dwLimitTime - dwCurrentTime) / 1000));
      |                                                                                                                           ^
In file included from /usr/local/lib/gcc9/include/c++/algorithm:62,
                 from stdafx.h:19,
                 from input_main.cpp:1:
/usr/local/lib/gcc9/include/c++/bits/stl_algo.h:3456:5: note: candidate: 'template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)'
 3456 |     max(initializer_list<_Tp> __l)
      |     ^~~
/usr/local/lib/gcc9/include/c++/bits/stl_algo.h:3456:5: note:   template argument deduction/substitution failed:
input_main.cpp:2289:123: note:   mismatched types 'std::initializer_list<_Tp>' and 'int'
 2289 |   ch->ChatPacket(CHAT_TYPE_INFO, "<RemoteShop> You have to wait %u sec.", std::max(1, (dwLimitTime - dwCurrentTime) / 1000));
      |                                                                                                                           ^
In file included from /usr/local/lib/gcc9/include/c++/algorithm:62,
                 from stdafx.h:19,
                 from input_main.cpp:1:
/usr/local/lib/gcc9/include/c++/bits/stl_algo.h:3462:5: note: candidate: 'template<class _Tp, class _Compare> _Tp std::max(std::initializ                      er_list<_Tp>, _Compare)'
 3462 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/usr/local/lib/gcc9/include/c++/bits/stl_algo.h:3462:5: note:   template argument deduction/substitution failed:
input_main.cpp:2289:123: note:   mismatched types 'std::initializer_list<_Tp>' and 'int'
 2289 |   ch->ChatPacket(CHAT_TYPE_INFO, "<RemoteShop> You have to wait %u sec.", std::max(1, (dwLimitTime - dwCurrentTime) / 1000));`

**Comment by blackdragonx61** [comment]
can you try MAX or std::max

**Comment by DemOnJR** [comment]
Solved: max > MAX
